title: Wenxuan Wang's Homepage
page-top-title: Wenxuan Wang
top-section-bg-text: Mechanical Engineering
home-subtitle: Wenxuan Wang&ensp;|&ensp;王文轩
copyright-text: '&copy; Wenxuan Wang 2023-2024. All Rights Reserved.
 Thanks to Tao Li's Template.
