title: Wenxuan Wang's Homepage
page-top-title: Wenxuan Wang
top-section-bg-text: Mechanical Engineering
home-subtitle: <i class="bi bi-house-fill"></i>&nbsp;HOME
copyright-text: '&copy; Wenxuan Wang 2023-2024. All Rights Reserved. Thanks to Tao Li\'s Template.'
